config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  resources :courses
  resources :users, only: [:index]

  root 'home#index'
  get 'home/activity'
  get 'home/index'


  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # get 'static_page/landing_page'
  # get 'static_page/privacy_policy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  # them gem friendly_id, sua name thanh title
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, :short_description, :language, :level, :price,  presence: true
  validates :description, presence: true, length: { :minimum => 5 }

  # tao moi quan he 1 course co nhieu user
  belongs_to :user

  def to_s
    title
  end

  LANGUAGES = [:"English",:"Polish",:"Russian"]
  def self.languages
    LANGUAGES.map { |language| [language, language]}
  end

  LEVELS = [:"Beginner",:"Imediate",:"Advanced"]
  def self.levels
    LEVELS.map { |level|[level, level]}
  end 
  # tao form rich text action
  has_rich_text :description

  #  them gem public 
  include PublicActivity::Model
  tracked owner: Proc.new{|controller, model| controller.current_user}
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
             
  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  # rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable
         #  Them :trackable de dam bao chong su tan cong login nhieu lan vao he thong
         #  them confirmable de khi dang ky co xac minh qua email
 
  # gem rolify tao ra
  rolify :before_add => :before_add_method

  def before_add_method(role)
    # do something before it gets added
  end
  
  def to_s
    email
  end

  def username
    self.email.split(/@/).first
  end
  has_many :courses 

  after_create :assign_default_role

  def assign_default_role
    if User.count == 1  
      self.add_role(:admin) if self.roles.blank?
      self.add_role(:teacher)
      self.add_role(:student)
    else
      self.add_role(:student) if self.roles.blank?
      self.add_role(:teacher)

    end

  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  
  include PublicActivity::StoreController #save current_user using gem public_activity
  before_action :set_global_variables, if: :user_signed_in?


  def set_global_variables
    @ransack_courses = Course.ransack(params[:course_search], search_key: :course_search)
  end 
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
   
    # if params[:title]

    #   @courses = Course.where('title LIKE ?', "%#{params[:title]}%")
    # else
    #   # @courses = Course.all
    #   @q = Course.ransack(params[:q])
    #   @courses = @q.result.includes(:user)
    # end
    
    @ransack_courses = Course.ransack(params[:courses_search], search_key: :courses_search)
    @courses = @ransack_courses.result.includes(:user)

  end

  # GET /courses/1 or /courses/1.json
  def show
    #  them .friendly de tim kiem show friendly
    @course = Course.friendly.find(params[:id])
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)
  
    @course.user_id = current_user.id    

    respond_to do |format|
      
      if @course.save
        format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title, :description, :short_description, :language, :level, :price)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index
    @courses = Course.all.limit(3);   
    @latest_courses = Course.all.limit(3).order(created_at: :desc);
  end

  def activity
    @activities = PublicActivity::Activity.all
  end


end

app/controllers/users_controller.rb
# Them devise trackable

class UsersController < ApplicationController
  def index
    # @users = User.all.order(created_at: :desc)
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/courses/_course.html.haml
.col
  .card
    .card-header 
      .fa.fa-book
      = link_to course.title, course_path(course)
    .card-body 
      = course.description 
      %small= simple_format(course.short_description)
    .card-footer
      %i.fa-solid.fa-earth-americas
      = course.language
      %i.fa-solid.fa-layer-group
      = course.level
      = number_to_currency(course.price) 
    .card-footer.card-display
      %div
        %i.fa-regular.fa-clock
        = course.created_at.strftime('%d-%b-%Y')
      %div 
        %i.fa-solid.fa-chalkboard-user
        = course.user.username  
        
    .card-footer
      = link_to 'Show', course, class: 'btn btn-sm btn-primary'
      = link_to 'Edit', edit_course_path(course), class: 'btn btn-sm btn-warning'
      = link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'

app/views/courses/_form.html.haml
= simple_form_for(@course) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title, class: 'form-control'
    = f.label :description
    = f.rich_text_area :description, class: 'form-control'
    %small= f.error :description, class: 'is-invalid'
    = f.input :short_description, class: 'form-control'
    = f.input :language, class: 'form-control', collection: ["English","Polish","Russian"]
    = f.input :level, class: 'form-control', collection: ["Beginner","Imediate","Advanced"]
    = f.input :price, class: 'form-control'


  
  .form-actions
    = f.button :submit, class: 'btn btn-primary btn-common'

app/views/courses/edit.html.haml
%h2 
  .text-center
    Editing course  
%p

  = render 'form'

  = link_to 'Show', @course
  \|
  = link_to 'Back', courses_path

app/views/courses/index.html.haml
%h2 
  .text-center
    Courses 
    .badge.text-bg-success
      = Course.count   
%p


.row
  .col-md-2
    -# = search_form_for @q do |f|
    = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
      = f.label :Title
      = f.search_field :title_cont, placeholder: 'title', class: 'form-control'
      = f.label :Description
      = f.search_field :short_description_cont, placeholder: 'Short description', class: 'form-control'
      = f.label :Language
      -# = f.search_field :language_cont, placeholder: 'language', class: 'form-control'
      = f.select :language_cont, Course.languages, include_blank: true, class: 'form-control'
      -# = f.select :language_cont,['English','Polish','Russian'] , include_blank: true, class: 'form-control'
      %br
      = f.label :Level
      -# = f.search_field :level_cont, placeholder: 'level', class: 'form-control'
      = f.select :level_cont, Course.levels, include_blank: true, class: 'form-control'
      %br
      = f.label :Price
      = f.search_field :price_eq, placeholder: 'price', class: 'form-control'
      = f.label :Teaching
      = f.search_field :user_email_cont, placeholder: 'User email', class: 'form-control'
      = f.submit 'search', class: 'btn btn-primary'
    = link_to 'refresh', courses_path
  .col-md-10
    .row.row-cols-1.row-cols-md-3.g-4
      - @courses.each do |course|
        = render 'courses/course', course: course

app/views/courses/new.html.haml
%h2 
  .text-center
    New course  
%p
= render 'form'

= link_to 'Back', courses_path, class: 'btn btn-info btn-common'

app/views/courses/show.html.haml
= link_to 'Courses', courses_path
\|
= link_to @course.title, course_path(@course)
%p
= render 'courses/course', course: @course

app/views/home/activity.html.haml
%h2 
  .text-center
    Activity 
    .badge.text-bg-success
      = @activities.count    
%p
%ul.list-group
  - @activities.each do |activity|
    %li.list-group-item
      = activity.id
      = activity.trackable_type
      = activity.trackable_id
      = link_to activity.trackable, activity.trackable, class: 'text-primary'
      = activity.key
      = activity.parameters
      = activity.owner

app/views/home/index.html.haml
.container
  .jumbotron 
    .display-4 
      What do you want to learn today?

    .p-4 
      .form-inline.my-2.my-lg-0
        = form_tag(courses_path, method: :get) do
          .input-group
            = text_field_tag :title, params[:title], autocomplete: 'off', placeholder: "Search", class: 'form-control-sm'
            %span.input-group-append
              %button.btn.btn-primary.btn-sm.btn-gem{:type => "submit"}
                %span.fa.fa-search{"aria-hidden" => "true"}
  .card-group
    .card.card-body
      %h1
        .fa.fa-graduation-cap
      = Course.count
      online courses
      .row
      Explore a variety of fresh topics
    .card.card-body
      %h1
        .fa.fa-chalkboard-teacher
        /.fa.fa-brain
      = Course.distinct.count(:user_id)
      expert instructors
      .row
      Find the right instructor for you
    .card.card-body
      %h1
        .fa.fa-user-graduate
      = User.count
      active learners
      .row
      Join the knowledge sharing community
    .card.card-body
      %h1
        .fa.fa-infinity
      Lifetime access
      .row
      Learn on your schedule

  %hr
  %h2 
    Popular courses  
  .row.row-cols-1.row-cols-md-3.g-4
    - @courses.each do |course|
      = render 'courses/course', course: course
  %hr
  %h2  
    Top rated Courses
  .row.row-cols-1.row-cols-md-3.g-4
    - @courses.each do |course|
      = render 'courses/course', course: course
  %hr
  %h2
    Latest courses
  .row.row-cols-1.row-cols-md-3.g-4
    - @latest_courses.each do |course|
      = render 'courses/course', course: course
  
  
  

app/views/layouts/_footer.html.haml
%footer.bg-footer
  .container
    .row
      .col-md-4.text-
        Copyright
        © 
        = Time.now.year
        CoursePlatform Sp. z o.o.
        .row
        .fa.fa-envelope.text-dark
        = mail_to 'khuyenho93@gmail.com'
        .row
      .col-md-4.text-dark
        Privacy policy
        .row
        Terms and conditions
      .col-md-4.text-dark
        About us
        .row
        = link_to 'Teach on CoursePlatform', new_course_path

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  %a.navbar-brand{:href => "#"} Rubygems
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    - if current_user
      %ul.navbar-nav.mr-auto
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(root_path)}"}
          = link_to root_path, class: 'nav-link' do
            .fa.fa-home
            Home
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(courses_path)}"}
          = link_to courses_path, class: 'nav-link' do
            .fa.fa-book
            Courses
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(new_course_path)}"}
          = link_to new_course_path, class: 'nav-link' do
            .fa.fa-plus
            New Course
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(users_path)}"}
          = link_to users_path, class: 'nav-link' do
            .fa.fa-user
            Users
        

      -# - if current_page?(courses_path)     
      .form-inline.my-2.my-lg-0
        -# = search_form_for @q do |f|        
        = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
          .input-group
            = f.search_field :title_cont, autocomplete: 'off', placeholder: "Search", class: 'form-control-sm'
            %span.input-group-append
              %button.btn.btn-primary.btn-sm.btn-gem{:type => "submit"}
                %span.fa.fa-search{"aria-hidden" => "true"}

        -# = form_tag(courses_path, method: :get) do     
        -#   .input-group
        -#     = text_field_tag :title, params[:title], autocomplete: 'off', placeholder: "Search", class: 'form-control-sm'
        -#     %span.input-group-append
        -#       %button.btn.btn-primary.btn-sm.btn-gem{:type => "submit"}
        -#         %span.fa.fa-search{"aria-hidden" => "true"}
      %ul.navbar-nav.mr-auto.mr-right
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(home_activity_path)}"}
          = link_to home_activity_path, class: 'nav-link' do
            .fa.fa-bell
            Activity
        %li.nav-item.dropdown
          %a.nav-link.dropdown-toggle{"aria-expanded" => "false",
           "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
            %b= current_user.email
          %ul.dropdown-menu
            %li
              = link_to edit_user_registration_path, class: "dropdown-item" do
                .fa.fa-cog
                %b Account settings
            %li
              = link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do
                .fa.fa-sign-out-alt
                %b Sign out
    - else
      %ul.navbar-nav
        %li.nav-item= link_to 'Sign Up', new_user_registration_path, class: 'nav-link '
        %li.nav-item= link_to 'Log In', new_user_session_path, class: 'nav-link'

app/views/layouts/_message.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert  alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role => "alert"}
    
      -# %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"}x
      = content_tag :div, msg, :id => "flash_#{name}" 

      

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RubyGemBootcamp
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    
    .container
      %p
      = render 'layouts/message'
      = yield
    %br
    = render 'layouts/footer'
      
      

app/views/static_page/landing_page.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    %a.navbar-brand{:href => "#"}
      %i.fa-solid.fa-house
      Navbar
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.me-auto.mb-2.mb-lg-0
        %li.nav-item
          %a.nav-link.active{"aria-current" => "page", :href => "#"} Home
        %li.nav-item
          %a.nav-link{:href => "#"} Link
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
            Dropdown
          %ul.dropdown-menu{"aria-labelledby" => "navbarDropdown"}
            %li
              %a.dropdown-item{:href => "#"} Action
            %li
              %a.dropdown-item{:href => "#"} Another action
            %li
              %hr.dropdown-divider/
            %li
              %a.dropdown-item{:href => "#"} Something else here
        %li.nav-item
          %a.nav-link.disabled{"aria-disabled" => "true", :href => "#", :tabindex => "-1"} Disabled
      %form.d-flex
        %input.form-control.me-2{"aria-label" => "Search", :placeholder => "Search", :type => "search"}/
        %button.btn.btn-outline-success{:type => "submit"} Search
.container-fluid
  / Content here
  %h1 hello
  = link_to "Privacy Policy", privacy_policy_path, class: "btn btn-lg btn-warning"
  = link_to privacy_policy_path, class: "btn btn-lg btn-warning" do
    %i.fa-solid.fa-book
    Privacy Policy

app/views/users/_user.html.haml
.card 
  .card-header 
    .fa.fa-user 
    = user.email 
  .card-footer 
    Signed up
    = time_ago_in_words(user.created_at)
    ago 
    .row
  .card-footer 
    = 'sign_in_count'.humanize
    = user.sign_in_count
    %br
    = 'current_sign_in_at'.humanize
    = user.current_sign_in_at
    %br
    = 'last_sign_in_at'.humanize
    = user.last_sign_in_at
    %br
    = 'current_sign_in_ip'.humanize
    = user.current_sign_in_ip
    %br
    = 'last_sign_in_ip'.humanize
    = user.last_sign_in_ip
  .card-footer
    Confirmed email?
    - if user.confirmed_at.present?
      .btn.btn-success Yes
    - else
      .btn.btn-danger No
  .card-footer
    - user.roles.each do |role|
      .badge.text-bg-info
        = role.name

app/views/users/index.html.haml
%h2 
  .text-center
    Users 
    .badge.text-bg-success
      = @users.count   
%p
.row.row-cols-1.row-cols-md-3.g-4
  - @users.each do |user|    
    = render 'users/user', user: user

.form-inline
  = search_form_for @q do |f|
    = f.search_field :email_cont, placeholder: 'email'
    = f.search_field :sign_in_count_eq, placeholder: 'sign in count'
    = f.search_field :email_or_sign_in_count_eq, placeholder: 'email or sign in count'
    = f.submit
  .ml-2
  = link_to 'refresh', users_path

%table.table.table-bordered
  %thead
    %tr
      %th id
      %th= sort_link(@q, :email)
      %th created_at
      %th= 'sign_in_count'.humanize
      %th= 'current_sign_in_at'.humanize
      %th= 'last_sign_in_at'.humanize
      %th= 'current_sign_in_ip'.humanize
      %th= 'last_sign_in_ip'.humanize
  %tbody
    - @users.each do |user|
      %tr
        %td= user.id
        %td= user.email
        %td= user.created_at
        %td= user.sign_in_count
        %td= user.current_sign_in_at
        %td= user.last_sign_in_at
        %td= user.current_sign_in_ip
        %td= user.last_sign_in_ip